from . import menu
from . import backs
from . import courses_all
from . import text_handler
from . import anketa
from . import content_types
from . import fake_startREG
from . import LangChange
from . import start
from . import echo