from . import fake_startREG
from . import menu
from . import backs
from . import admin
from . import commands
from . import courses_all
from . import content_types
from . import LangChange
from . import start